# https://github.com/btford/write-good
name: btford write-good
on: [push]
   
jobs:
  writing-good:
    name: Try the write good feature
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "is this action working?"
      - uses: btford/write-good@
