# https://github.com/btford/write-good
name: btford write-good

on:
  push:
    branches: [ main ]
  pull requests:
   branches: [ main ]
   
jobs:
  writing-good:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run echo "is this action working?"
      - uses: btford/write-good@1.0.8
