# https://github.com/btford/write-good
name: btford write-good
on:
  push:
    branches: [main]
  pull_request: 
    branches: [main]
    
jobs:
  writing-good:
    name: Try the write good feature
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      #- run: echo "is this action working?"
      - run: touch write_good.txt
      - run: sudo npm install -g write-good
      - run: write-good ${{ github.workspace }}/testingwritegood.md >> write_good.txt
